name: task_manager
description: "Новый Flutter-проект."
# Следующая строка предотвращает случайную публикацию пакета на pub.dev с помощью `flutter pub publish`. 
# Это предпочтительно для частных пакетов.
publish_to: 'none' # Удалите эту строку, если вы хотите опубликовать на pub.dev

# Ниже определяется версия и номер сборки для вашего приложения.
# Номер версии - это три числа, разделенные точками, например 1.2.43,
# с последующим необязательным номером сборки, разделенным знаком плюс.
# И номер версии, и номер сборки могут быть переопределены в flutter
# build путем указания --build-name и --build-number соответственно.
# В Android build-name используется как versionName, а build-number как versionCode.
# Подробнее о версионировании Android см. по адресу https://developer.android.com/studio/publish/versioning
# В iOS build-name используется как CFBundleShortVersionString, а build-number как CFBundleVersion.
# Подробнее о версионировании iOS см. по адресу
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# В Windows build-name используется как основные, второстепенные и исправленные части
# версий продукта и файла, а build-number используется как суффикс сборки.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Зависимости указывают на другие пакеты, которые вашему пакету необходимы для работы.
# Чтобы автоматически обновить зависимости вашего пакета до последних версий,
# рассмотрите возможность запуска `flutter pub upgrade --major-versions`. В качестве альтернативы,
# зависимости можно обновить вручную, изменив номера версий ниже на
# последнюю версию, доступную на pub.dev. Чтобы увидеть, какие зависимости имеют более новые
# версии, запустите `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Следующая строка добавляет шрифт Cupertino Icons в ваше приложение.
  # Используйте с классом CupertinoIcons для значков в стиле iOS.
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.0
  # recaptcha_enterprise_flutter: ^18.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Пакет "flutter_lints" ниже содержит набор рекомендуемых линтеров для
  # поощрения хороших практик кодирования. Набор линтеров, предоставляемый пакетом,
  # активирован в файле `analysis_options.yaml`, расположенном в корне вашего
  # пакета. См. этот файл для получения информации о деактивации конкретных правил линтера
  # и активации дополнительных.
  flutter_lints: ^3.0.0

# Для получения информации о общей части Dart этого файла см.
# следующую страницу: https://dart.dev/tools/pub/pubspec

# Следующий раздел специфичен для пакетов Flutter.
flutter:

  # Следующая строка гарантирует, что шрифт Material Icons
  # включен в ваше приложение, чтобы вы могли использовать значки в
  # классе Material Icons.
  uses-material-design: true

  # Чтобы добавить ресурсы в ваше приложение, добавьте раздел ресурсов, например:
  assets:
  - assets/avatar.jpg

  # Ресурс изображения может ссылаться на один или несколько вариантов, зависящих от разрешения, см.
  # https://flutter.dev/assets-and-images/#resolution-aware

  # Для получения подробной информации о добавлении ресурсов из зависимостей пакетов см.
  # https://flutter.dev/assets-and-images/#from-packages

  # Чтобы добавить пользовательские шрифты в ваше приложение, добавьте раздел шрифтов здесь,
  # в этом разделе "flutter". Каждая запись в этом списке должна иметь
  # ключ "family" с именем семейства шрифтов и ключ "fonts" со
  # списком, содержащим ресурс и другие описатели для шрифта. Например:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Для получения подробной информации о шрифтах из зависимостей пакетов,
  # см. https://flutter.dev/custom-fonts/#from-packages

